(()=>{
const CW_BUS_URL='https://gdycbluljgfezhgslppe.supabase.co/functions/v1/cw-bus';
function dir(){let j=getJourneyIntent();if(j.includes('Singapore from JB'))return'jb-sg';if(j.includes('JB from Singapore'))return'sg-jb';return live.location?.name==='Johor area'?'jb-sg':'sg-jb'}
function card(){if(document.querySelector('[data-widget="cwbus"]'))return;let after=document.querySelector('[data-widget="transport"]');if(!after)return;let a=document.createElement('article');a.className='card homeWidget';a.dataset.widget='cwbus';a.innerHTML='<div class="head"><div class="title">🚌 Causeway Link CW</div><span id="cwBadge" class="tag">Loading</span></div><div id="cwDirection" class="sub">Checking published cross-border schedule…</div><div id="cwBusList" class="cwBusList"><div class="sub">Connecting to Causeway Link schedule data…</div></div><button class="miniBtn transitRefresh" onclick="loadCWBus(this)">↻ Refresh CW schedule</button><div id="cwTime" class="trafficMeta">Scheduled status only · not live GPS.</div>';after.after(a)}
function render(j){let d=j?.direction||dir(),label=d==='jb-sg'?'🇲🇾 JB → 🇸🇬 Singapore':'🇸🇬 Singapore → 🇲🇾 JB';txt('cwBadge',j?.directory_checked?'Published':'Schedule');txt('cwDirection',label+' · Causeway Link published operating hours');let box=$('cwBusList'),routes=Array.isArray(j?.routes)?j.routes:[];if(!box)return;if(!routes.length){box.innerHTML='<div class="sub">CW schedule is temporarily unavailable.</div>';return}let key=d==='jb-sg'?'jb_to_sg':'sg_to_jb',score={operating:0,ending_soon:1,starting_soon:2,not_scheduled:3};routes=[...routes].sort((a,b)=>(score[a.selected_status?.code]??9)-(score[b.selected_status?.code]??9));box.innerHTML=routes.map(r=>{let st=r.selected_status||{},side=r[key]||{},listed=r.listed_on_causewaylink===true?' · Listed on Causeway Link':r.listed_on_causewaylink===false?' · Not in current directory':'';return `<div class="cwRoute"><div class="cwRouteTop"><div class="cwRouteNo">${esc(r.id)}</div><span class="cwState ${esc(st.code||'')}">${esc(st.label||'Schedule')}</span></div><div class="cwRouteMeta">Board at ${esc(side.stop||'published stop')} · ${esc(r.via||'Cross-border')}</div><div class="cwRouteSub">${esc(r.interval||'Published interval')} · ${esc(st.detail||'Check schedule')}${esc(listed)}</div></div>`}).join('');txt('cwTime','Checked '+new Date(j.fetched_at||Date.now()).toLocaleTimeString('en-SG',{hour:'2-digit',minute:'2-digit'})+' · published timetable · scheduled status, not live ETA')}
window.loadCWBus=async function(btn=null){if(btn)setBusy(btn,true);txt('cwBadge','Loading');try{let r=await fetch(CW_BUS_URL+'?direction='+encodeURIComponent(dir()),{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error();live.cw=j;render(j)}catch{txt('cwBadge','Unavailable');let b=$('cwBusList');if(b)b.innerHTML='<div class="sub">Could not load Causeway Link schedule right now.</div>'}finally{if(btn)setBusy(btn,false)}};
let css=document.createElement('style');css.textContent='.cwBusList{display:flex;flex-direction:column;gap:9px;margin-top:12px}.cwRoute{padding:11px 12px;border:1px solid #e7ebf3;border-radius:16px;background:#fff}.cwRouteTop{display:flex;align-items:center;justify-content:space-between;gap:10px}.cwRouteNo{font-size:16px;font-weight:900}.cwState{font-size:10px;font-weight:900;border-radius:99px;padding:5px 8px;background:#eef3ff;color:#5267ad;white-space:nowrap}.cwState.operating{background:#edf9f0;color:#247247}.cwState.ending_soon,.cwState.starting_soon{background:#fff6e6;color:#9a6415}.cwState.not_scheduled{background:#f3f4f7;color:#737b8b}.cwRouteMeta{font-size:12px;color:#617089;margin-top:5px;line-height:1.45}.cwRouteSub{font-size:11px;color:#8a94a7;margin-top:3px;line-height:1.4}';document.head.appendChild(css);
card();
try{live.cw=null;HOME_WIDGETS.splice(2,0,{id:'cwbus',label:'🚌 Causeway Link CW'});applyHomeWidgets()}catch{}
try{let base=aiContext;aiContext=function(){let c=base();if(homeWidgetEnabled('cwbus')&&live.cw)c.causeway_link_bus={direction:live.cw.direction,scheduled_only:true,disclaimer:live.cw.disclaimer,routes:(live.cw.routes||[]).map(r=>({id:r.id,via:r.via,interval:r.interval,listed_on_causewaylink:r.listed_on_causewaylink,selected_status:r.selected_status}))};return c}}catch{}
loadCWBus();
})();