from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')
if 'runSGD v1.6.8' in s: raise SystemExit('already patched')
s=s.replace('runSGD v1.6.7','runSGD v1.6.8').replace('RunSGD v1.6.7','RunSGD v1.6.8').replace('>v1.6.7<','>v1.6.8<')

css='''\n.kbGrid{display:flex;flex-direction:column;gap:11px}.kbCard{background:#fffffff2;border:1px solid #fff;border-radius:20px;padding:15px;box-shadow:0 8px 24px #46537d0d}.kbHead{display:flex;align-items:center;gap:12px;cursor:pointer}.kbIcon{width:42px;height:42px;border-radius:14px;display:grid;place-items:center;font-size:21px;background:linear-gradient(120deg,#eef7ff,#f6efff);flex:0 0 auto}.kbMain{min-width:0;flex:1}.kbTitle{font-weight:850;font-size:16px;line-height:1.25}.kbSummary{font-size:12px;color:#748097;line-height:1.4;margin-top:3px}.kbChevron{font-size:17px;color:#8190aa;transition:transform .18s ease}.kbCard.open .kbChevron{transform:rotate(180deg)}.kbBody{display:none;padding:12px 0 1px 54px}.kbCard.open .kbBody{display:block}.kbBody ul{margin:0;padding-left:18px;color:#58647a;font-size:13px;line-height:1.55}.kbBody li+li{margin-top:5px}.kbSource{display:inline-block;margin-top:10px;color:#4965c7;text-decoration:none;font-size:11px;font-weight:800}.kbChecked{font-size:10px;color:#96a0b2;margin-top:7px}.kbIntro{padding:14px 15px;border-radius:18px;background:linear-gradient(120deg,#eef7ff,#f7f1ff,#fff7ef);margin-bottom:12px}.kbIntro strong{font-size:15px}.kbIntro .sub{margin-top:4px}\n'''
s=s.replace('</style>',css+'</style>',1)

old='''<section id="explore" class="page">\n<h2 class="pageTitle">Explore</h2>\n<p class="sub">Live discovery for your JB ↔ Singapore routine.</p>\n<div class="tabs">\n  <button class="chip" data-explore="know" onclick="showExplore('know')">✨ For You</button>\n  <button class="chip" data-explore="news" onclick="showExplore('news')">📰 News</button>\n  <button class="chip" data-explore="shopping" onclick="showExplore('shopping')">🛍 Shopping</button>\n  <button class="chip" data-explore="events" onclick="showExplore('events')">🎟 Events</button>\n</div>\n<div class="feedbar"><span id="feedStatus" class="sub">Live sources</span><button class="feedRefresh" onclick="refreshExplore(this)">↻ Refresh</button></div>\n<div id="exploreFeed" class="feed"></div>\n</section>'''
new='''<section id="explore" class="page">\n<h2 class="pageTitle">Explore</h2>\n<p class="sub">Quick commuter knowledge first. Live discovery when you need it.</p>\n<div class="tabs">\n  <button class="chip" data-explore="know" onclick="showExplore('know')">📚 Knowledge</button>\n  <button class="chip" data-explore="news" onclick="showExplore('news')">📰 News</button>\n  <button class="chip" data-explore="shopping" onclick="showExplore('shopping')">🛍 Shopping</button>\n  <button class="chip" data-explore="events" onclick="showExplore('events')">🎟 Events</button>\n</div>\n<div class="feedbar"><span id="feedStatus" class="sub">RunSGD knowledge base</span><button id="feedRefreshBtn" class="feedRefresh" onclick="refreshExplore(this)">↻ Refresh</button></div>\n<div id="exploreFeed" class="feed"></div>\n</section>'''
if old not in s: raise SystemExit('explore block not found')
s=s.replace(old,new,1)

anchor="function signalCards(){let c=[],r=Math.max(live.weather.SG?.rain||0,live.weather.JB?.rain||0);"
kb="""const knowledgeBase=[
 {icon:'🚦',title:'Crossing timing & queue',summary:'When should I cross Woodlands or Tuas?',body:['There is no fixed “best time” — queues change quickly with peak hours, weekends and holidays.','Check the RunSGD Causeway snapshot before leaving and add buffer when traffic looks heavy.','For time-sensitive trips, compare both Woodlands and Tuas before committing.'],source:'https://www.ica.gov.sg/news-and-publications/newsroom/media-release/105',sourceLabel:'ICA travel tips'},
 {icon:'🚌',title:'Bus, train or car?',summary:'Pick the option that matches your trip.',body:['Bus is the most flexible option and serves both First Link and Second Link.','Train can avoid road congestion but depends on ticket availability and fixed departure times.','Driving gives flexibility, but you need vehicle-entry requirements, toll/payment readiness and parking.'],source:'https://www.causewaylink.com.my/cross-border-travel-guide/',sourceLabel:'Causeway Link guide'},
 {icon:'🛂',title:'Passport, MDAC & e-Gate',summary:'Keep immigration simple before you leave.',body:['Carry your own valid passport and check its remaining validity before travelling.','Foreign visitors who need MDAC should submit it through the official Malaysia Immigration portal within the required window.','Malaysia e-Gate eligibility depends on nationality, passport type and traveller status — check before relying on it.'],source:'https://imigresen-online.imi.gov.my/mdac/main',sourceLabel:'Official MDAC portal'},
 {icon:'🚗',title:'Driving to JB: VEP basics',summary:'The short checklist for Singapore vehicles.',body:['Foreign vehicles entering Malaysia must be registered for VEP with JPJ.','Keep valid vehicle insurance and required vehicle documents current.','Your VEP RFID tag is vehicle-specific; check its status before a driving trip.'],source:'https://www.jpj.gov.my/pelaksanaan-sistem-kutipan-caj-jalan-rc-dan-rekod-kemasukan-kenderaan-asing-vep/',sourceLabel:'JPJ VEP'},
 {icon:'🛍️',title:'Shopping & bringing items back',summary:'Know the Singapore GST relief before buying.',body:['For eligible travellers, GST import relief is up to S$100 when away for less than 48 hours and up to S$500 for 48 hours or more.','Some Singapore pass holders are not eligible for this GST import relief.','Keep receipts and declare taxable or dutiable goods when required; Customs@SG can be used before arrival.'],source:'https://www.customs.gov.sg/at-customs/arriving-in-singapore/duty-free-concession-gst-relief/',sourceLabel:'Singapore Customs'},
 {icon:'💱',title:'SGD ↔ MYR money basics',summary:'Reference rate is not the same as your cash rate.',body:['RunSGD shows a reference SGD/MYR market rate for comparison.','Money changers, cards and remittance services use their own spread or fees, so the final rate can differ.','Compare the amount you actually receive, not only the advertised headline rate.'],source:'',sourceLabel:''}
];
function toggleKb(i){let c=document.querySelector('[data-kb="'+i+'"]');if(c)c.classList.toggle('open')}
function renderKnowledge(){let f=$('exploreFeed');if(!f)return;let refresh=$('feedRefreshBtn');if(refresh)refresh.style.display='none';txt('feedStatus','Quick guides · checked Sep 2026');f.innerHTML='<div class="kbIntro"><strong>📚 SG ↔ JB commuter knowledge</strong><div class="sub">Short, practical guides. AI search will come later.</div></div><div class="kbGrid">'+knowledgeBase.map((a,i)=>`<article class="kbCard" data-kb="${i}"><div class="kbHead" onclick="toggleKb(${i})"><div class="kbIcon">${a.icon}</div><div class="kbMain"><div class="kbTitle">${esc(a.title)}</div><div class="kbSummary">${esc(a.summary)}</div></div><div class="kbChevron">⌄</div></div><div class="kbBody"><ul>${a.body.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${a.source?`<a class="kbSource" target="_blank" rel="noopener" href="${a.source}">${esc(a.sourceLabel)} ↗</a>`:''}<div class="kbChecked">Quick reference · rules can change</div></div></article>`).join('')+'</div>'}
"""
if anchor not in s: raise SystemExit('signal anchor not found')
s=s.replace(anchor,kb+anchor,1)

old_show="function showExplore(type,force=false){localStorage.setItem('runsgdExploreTab',type);document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x.dataset.explore===type));let f=$('exploreFeed');if(!f)return;if(type==='know'){txt('feedStatus','Based on your current signals');f.innerHTML=signalCards().map(c=>`<div class=\"feedcard\"><span class=\"feedtag\">WHAT SHOULD I KNOW?</span><h3>${c[0]}</h3><div class=\"sub\">${c[1]}</div></div>`).join('');return}let cached=live.feeds[type];if(cached?.length&&!force){renderFeed(type,cached,'Live');return}loadDiscover(type)}"
new_show="function showExplore(type,force=false){localStorage.setItem('runsgdExploreTab',type);document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x.dataset.explore===type));let f=$('exploreFeed'),refresh=$('feedRefreshBtn');if(!f)return;if(type==='know'){renderKnowledge();return}if(refresh)refresh.style.display='inline-block';let cached=live.feeds[type];if(cached?.length&&!force){renderFeed(type,cached,'Live');return}loadDiscover(type)}"
if old_show not in s: raise SystemExit('showExplore not found')
s=s.replace(old_show,new_show,1)

p.write_text(s,encoding='utf-8')
print('patched v1.6.8')
