from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')
if 'runSGD v1.6.4' in s: raise SystemExit('already patched')
s=s.replace('runSGD v1.6.3','runSGD v1.6.4').replace('RunSGD v1.6.3','RunSGD v1.6.4').replace('>v1.6.3<','>v1.6.4<')

css='''\n.profileCard{display:none}.profileTop{display:flex;align-items:center;gap:14px;margin-bottom:14px}.profileAvatar{width:70px;height:70px;border-radius:22px;object-fit:cover;background:linear-gradient(120deg,#eef5ff,#f5efff);border:1px solid #e6eaf2}.profileFields{display:flex;flex-direction:column;gap:10px}.profileFields input,.profileFields textarea{width:100%;border:1px solid #e2e7f1;background:#fff;border-radius:14px;padding:12px;color:#17213b}.profileFields textarea{min-height:82px;resize:vertical}.badgeTag{display:inline-flex;align-items:center;border-radius:99px;padding:5px 9px;font-size:10px;font-weight:900;background:#eef3ff;color:#5067b4;text-transform:uppercase;letter-spacing:.3px}.badgeTag.admin{background:#fff0f2;color:#a33e53}.chatIdentity{display:flex;align-items:center;gap:7px;min-width:0}.chatAvatar{width:24px;height:24px;border-radius:8px;object-fit:cover;background:#eef3ff;flex:0 0 auto}.chatBadge{font-size:8px;font-weight:900;text-transform:uppercase;border-radius:99px;padding:2px 5px;background:#eef3ff;color:#5067b4}.chatBadge.admin{background:#fff0f2;color:#a33e53}\n'''
s=s.replace('</style>',css+'</style>',1)

old='''<article class="card"><div class="title">RunSGD v1.6.4</div><p class="sub">Your last approved location, current page and Explore tab are stored in this browser.</p><button class="btn refresh" onclick="refreshAll(this)">↻ Refresh live data</button></article>\n\n<article id="adminSettingsCard"'''
new='''<article class="card"><div class="title">RunSGD v1.6.4</div><p class="sub">Your last approved location, current page and Explore tab are stored in this browser.</p><button class="btn refresh" onclick="refreshAll(this)">↻ Refresh live data</button></article>\n\n<article id="profileCard" class="card toolbox profileCard">\n  <div class="profileTop">\n    <img id="profileAvatar" class="profileAvatar" alt="Profile photo">\n    <div><div class="title">My profile</div><div id="profileEmail" class="sub"></div><div id="profileBadge" class="badgeTag">NEWBIE</div></div>\n  </div>\n  <div class="profileFields">\n    <input id="profileName" maxlength="40" placeholder="Display name">\n    <textarea id="profileBio" maxlength="160" placeholder="Short bio about you"></textarea>\n    <label class="miniBtn" style="text-align:center;cursor:pointer">Change profile photo<input id="profilePhoto" type="file" accept="image/jpeg,image/png,image/webp,image/gif" style="display:none" onchange="uploadProfilePhoto(this)"></label>\n    <button class="btn refresh" onclick="saveProfile(this)">Save profile</button>\n    <div id="profileStatus" class="status">Your tag is managed by RunSGD.</div>\n  </div>\n</article>\n\n<article id="adminSettingsCard"'''
if old not in s: raise SystemExit('more block not found')
s=s.replace(old,new,1)

s=s.replace("let communityUser=null,communityRooms=[],activeRoom=null,chatChannel=null,communityRole='member';","let communityUser=null,communityRooms=[],activeRoom=null,chatChannel=null,communityRole='member',communityProfile=null;")

old_apply="""async function applyMemberState(){let signed=!!communityUser;$('communityAuthCard').style.display=signed?'none':'block';$('communityComposer').style.display=signed?'flex':'none';$('signOutBtn').style.display=signed?'inline-block':'none';$('communityGuestHint').style.display=signed?'none':'block';let adminCard=$('adminSettingsCard');if(!signed){communityRole='member';if(adminCard)adminCard.style.display='none';txt('memberState','Guest mode');return}let name=await communityProfileName(communityUser),linked=await communityLinkedStatus(communityUser);communityRole=await communityRoleOf(communityUser);if(adminCard)adminCard.style.display=communityRole==='admin'?'block':'none';txt('memberState','Signed in as '+name+(communityRole==='admin'?' · Admin':'')+linked)}"""
new_apply="""async function applyMemberState(){let signed=!!communityUser;$('communityAuthCard').style.display=signed?'none':'block';$('communityComposer').style.display=signed?'flex':'none';$('signOutBtn').style.display=signed?'inline-block':'none';$('communityGuestHint').style.display=signed?'none':'block';let adminCard=$('adminSettingsCard'),profileCard=$('profileCard');if(!signed){communityRole='member';communityProfile=null;if(adminCard)adminCard.style.display='none';if(profileCard)profileCard.style.display='none';txt('memberState','Guest mode');return}let {data:p}=await sb.from('profiles').select('display_name,avatar_url,bio,badge,role').eq('id',communityUser.id).maybeSingle();communityProfile=p||{};let name=communityProfile.display_name||await communityProfileName(communityUser),linked=await communityLinkedStatus(communityUser);communityRole=communityProfile.role||await communityRoleOf(communityUser);if(adminCard)adminCard.style.display=communityRole==='admin'?'block':'none';if(profileCard){profileCard.style.display='block';$('profileName').value=name||'';$('profileBio').value=communityProfile.bio||'';txt('profileEmail',communityUser.email||'');let tag=communityRole==='admin'?'admin':(communityProfile.badge||'newbie');$('profileBadge').textContent=tag;$('profileBadge').classList.toggle('admin',communityRole==='admin');let av=communityProfile.avatar_url||communityUser.user_metadata?.avatar_url||communityUser.user_metadata?.picture||'';$('profileAvatar').src=av||'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%2270%22 height=%2270%22%3E%3Crect width=%2270%22 height=%2270%22 rx=%2222%22 fill=%22%23eef3ff%22/%3E%3Ctext x=%2235%22 y=%2243%22 text-anchor=%22middle%22 font-size=%2228%22%3E👤%3C/text%3E%3C/svg%3E'}txt('memberState','Signed in as '+name+' · '+(communityRole==='admin'?'Admin':labelBadge(communityProfile.badge||'newbie'))+linked)}"""
if old_apply not in s: raise SystemExit('applyMemberState not found')
s=s.replace(old_apply,new_apply,1)

s=s.replace(".select('id,message,created_at,user_id,profiles(display_name)')", ".select('id,message,created_at,user_id,profiles(display_name,avatar_url,badge,role)')")
old_render="""function renderCommunityMessages(items){let el=$('chatList');if(!el)return;if(!items.length){el.innerHTML='<div class=\"sub\" style=\"padding:12px\">No messages yet. Be the first commuter to say hello 👋</div>';return}el.innerHTML=items.map(m=>{let n=m.profiles?.display_name||'Commuter',d=new Date(m.created_at).toLocaleString('en-SG',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}),mine=m.user_id===communityUser?.id,remove=communityRole==='admin'?`<button class=\"moderateBtn\" onclick=\"deleteCommunityMessage(${Number(m.id)})\">Remove</button>`:'';return `<div class=\"chatMsg ${mine?'mine':''}\"><div class=\"chatMeta\"><span class=\"chatName\">${esc(n)}</span><span>${esc(d)}${remove}</span></div><div class=\"chatText\">${esc(m.message)}</div></div>`}).join('');el.scrollTop=el.scrollHeight}"""
new_render="""function labelBadge(v){return ({newbie:'Newbie',pro:'Pro',oldtimer:'Oldtimer',paid:'Paid'})[v]||'Newbie'}\nfunction renderCommunityMessages(items){let el=$('chatList');if(!el)return;if(!items.length){el.innerHTML='<div class=\"sub\" style=\"padding:12px\">No messages yet. Be the first commuter to say hello 👋</div>';return}el.innerHTML=items.map(m=>{let p=m.profiles||{},n=p.display_name||'Commuter',d=new Date(m.created_at).toLocaleString('en-SG',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}),mine=m.user_id===communityUser?.id,remove=communityRole==='admin'?`<button class=\"moderateBtn\" onclick=\"deleteCommunityMessage(${Number(m.id)})\">Remove</button>`:'',tag=p.role==='admin'?'Admin':labelBadge(p.badge||'newbie'),av=p.avatar_url||'';return `<div class=\"chatMsg ${mine?'mine':''}\"><div class=\"chatMeta\"><span class=\"chatIdentity\">${av?`<img class=\"chatAvatar\" src=\"${esc(av)}\" alt=\"\">`:''}<span class=\"chatName\">${esc(n)}</span><span class=\"chatBadge ${p.role==='admin'?'admin':''}\">${esc(tag)}</span></span><span>${esc(d)}${remove}</span></div><div class=\"chatText\">${esc(m.message)}</div></div>`}).join('');el.scrollTop=el.scrollHeight}"""
if old_render not in s: raise SystemExit('renderCommunityMessages not found')
s=s.replace(old_render,new_render,1)

insert_after="""async function deleteCommunityMessage(id){if(communityRole!=='admin')return;if(!confirm('Remove this community message?'))return;let {error}=await sb.from('community_messages').delete().eq('id',id);if(error){alert(error.message);return}await loadCommunityMessages()}\n"""
profile_js="""\nasync function saveProfile(btn){if(!communityUser)return;let name=$('profileName')?.value.trim(),bio=$('profileBio')?.value.trim();if(!name||name.length<2)return txt('profileStatus','Display name must be at least 2 characters.');setBusy(btn,true);let {error}=await sb.from('profiles').update({display_name:name,bio}).eq('id',communityUser.id);setBusy(btn,false);if(error)return txt('profileStatus',error.message);txt('profileStatus','Profile saved.');await applyMemberState();if(activeRoom)await loadCommunityMessages()}\nasync function uploadProfilePhoto(input){if(!communityUser||!input.files?.[0])return;let file=input.files[0];if(file.size>2097152){txt('profileStatus','Photo must be 2 MB or smaller.');input.value='';return}txt('profileStatus','Uploading photo…');let path=communityUser.id+'/avatar',r=await sb.storage.from('avatars').upload(path,file,{upsert:true,contentType:file.type||'image/jpeg'});if(r.error){txt('profileStatus',r.error.message);input.value='';return}let url=sb.storage.from('avatars').getPublicUrl(path).data.publicUrl+'?v='+Date.now();let {error}=await sb.from('profiles').update({avatar_url:url}).eq('id',communityUser.id);input.value='';if(error)return txt('profileStatus',error.message);txt('profileStatus','Profile photo updated.');await applyMemberState();if(activeRoom)await loadCommunityMessages()}\n"""
if insert_after not in s: raise SystemExit('delete function anchor not found')
s=s.replace(insert_after,insert_after+profile_js,1)

p.write_text(s,encoding='utf-8')
print('patched v1.6.4')
