import {inJb,adapt,Tracker,distance} from './core.mjs';
const $=id=>document.getElementById(id),say=t=>$('status').textContent=t,fmt=m=>m>=1000?(m/1000).toFixed(1)+' km':Math.round(m)+' m';
let map,origin,destination,route,tracker,startMarker,endMarker,car,watch=null,lastFix=null,select='end',following=true,busy=false,lastRequest=0,active=false,ready=false;
function controls(){for(const id of ['gps','pickStart','pickEnd'])$(id).disabled=busy||active;$('plan').disabled=busy||!ready||!origin||!destination;$('start').disabled=busy||!route||active;$('reroute').disabled=busy||!active||!lastFix;$('stop').disabled=!active;$('pickStart').classList.toggle('selected',select==='start');$('pickEnd').classList.toggle('selected',select==='end')}
function invalidate(){route=null;tracker=null;if(map?.getSource('route'))map.getSource('route').setData({type:'FeatureCollection',features:[]});$('command').textContent='CHOOSE YOUR ROUTE';$('distance').textContent='JB';$('road').textContent='Johor Bahru map test';$('then').textContent='Choose points to preview a route.';$('remaining').textContent='';controls()}
function setPoint(p,type){if(!inJb(p)){say('Choose a location within the JB test area.');return}invalidate();if(type==='start'){origin=p;startMarker?.remove();startMarker=new maplibregl.Marker({color:'#15865b'}).setLngLat(p).addTo(map)}else{destination=p;endMarker?.remove();endMarker=new maplibregl.Marker({color:'#e16043'}).setLngLat(p).addTo(map)}$('points').textContent='Start: '+(origin?origin.slice().reverse().map(x=>x.toFixed(5)).join(', '):'not selected')+' → Destination: '+(destination?destination.slice().reverse().map(x=>x.toFixed(5)).join(', '):'not selected');controls()}
function getGps(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(Error('Location is unavailable in this browser.'));navigator.geolocation.getCurrentPosition(p=>{if(Date.now()-p.timestamp>10000||p.coords.accuracy>40)return reject(Error('GPS is not accurate enough yet. Try outdoors or pick a start for preview.'));resolve(p)},e=>reject(Error(e.code===1?'Location permission denied. Allow location to start a GPS test.':'Unable to get a fresh GPS fix.')),{enableHighAccuracy:true,maximumAge:0,timeout:15000})})}
function fix(p){return {point:[p.coords.longitude,p.coords.latitude],accuracy:p.coords.accuracy,time:p.timestamp,heading:p.coords.heading,speed:p.coords.speed}}
async function requestRoute(from){if(busy)return;if(Date.now()-lastRequest<5000){say('Please wait a few seconds before requesting another route.');return}busy=true;controls();say('Calculating an independent driving route…');lastRequest=Date.now();try{const url='https://routing.openstreetmap.de/routed-car/route/v1/driving/'+from.join(',')+';'+destination.join(',')+'?overview=full&geometries=geojson&steps=true&alternatives=false&radiuses=75;75';const res=await fetch(url,{signal:AbortSignal.timeout(20000)});if(!res.ok)throw Error('Routing service unavailable ('+res.status+'). Try again later.');const data=await res.json();const fresh=adapt(data);if(distance(from,fresh.points[0])>100||distance(destination,fresh.points.at(-1))>100)throw Error('Selected point is too far from a routable road. Choose a road entrance.');route=fresh;tracker=new Tracker(route);map.getSource('route').setData({type:'Feature',properties:{},geometry:{type:'LineString',coordinates:route.points}});const b=new maplibregl.LngLatBounds();route.points.forEach(p=>b.extend(p));map.fitBounds(b,{padding:55,maxZoom:16,duration:600});$('command').textContent='ROUTE PREVIEW';$('distance').textContent=fmt(route.total);$('road').textContent='JB · independent driving route';$('then').textContent='About '+Math.ceil(route.duration/60)+' min · no live traffic';$('remaining').textContent='Press Start GPS test when at the route start.';say('Route ready · OSM / OSRM');}catch(e){say(e.name==='TimeoutError'?'Routing timed out. Try again.':e.message);if(active){stop(false);invalidate();say('Test stopped: '+e.message+' Preview a fresh route before restarting.')}}finally{busy=false;controls()}}
function display(p){lastFix=fix(p);if(!tracker||!active||busy)return;const state=tracker.update(lastFix);say(state.status);controls();if(!state.valid){car?.setLngLat(lastFix.point);return}if(!car){const el=document.createElement('div');el.className='car';el.textContent='↑';car=new maplibregl.Marker({element:el}).setLngLat(state.point).addTo(map)}car.setLngLat(state.point);car.setRotation(Number.isFinite(lastFix.heading)?lastFix.heading:0);if(following)map.easeTo({center:state.point,zoom:16.5,duration:700});$('command').textContent=state.next?.cue.text||'CONTINUE TO DESTINATION';$('arrow').textContent=state.next?.cue.icon||'◎';$('distance').textContent=fmt(state.turnDistance);$('road').textContent=state.next?.name||'Destination';const nextIndex=route.turns.indexOf(state.next),then=nextIndex>=0?route.turns[nextIndex+1]:null;$('then').textContent=then?'THEN · '+then.cue.text+' · '+then.name:'Continue to destination';$('remaining').textContent=fmt(state.remaining)+' remaining';if(state.arrived){stop(false);$('command').textContent='ARRIVED';$('distance').textContent='✓';say('Arrival confirmed by three accurate GPS fixes.')}}
function stop(message=true){if(watch!==null)navigator.geolocation.clearWatch(watch);watch=null;active=false;document.body.classList.remove('tracking');controls();if(message)say('GPS test stopped.');setTimeout(()=>map?.resize(),0)}
$('gps').onclick=async()=>{busy=true;controls();say('Getting your location…');try{const p=await getGps();setPoint(fix(p).point,'start');if(origin){map.flyTo({center:origin,zoom:15});say('Start set. Tap the map to choose a destination.')}}catch(e){say(e.message)}finally{busy=false;controls()}};
$('pickStart').onclick=()=>{select='start';say('Tap the map to choose a start.');controls()};$('pickEnd').onclick=()=>{select='end';say('Tap the map to choose your destination.');controls()};$('plan').onclick=()=>requestRoute(origin);
$('start').onclick=async()=>{busy=true;controls();say('Checking your current position…');try{const p=await getGps(),f=fix(p);if(!inJb(f.point))throw Error('GPS test requires your current location to be within JB. You can still preview routes.');if(distance(f.point,route.points[0])>100)throw Error('You are not at the route start. Set your current location as start and preview again.');tracker=new Tracker(route);active=true;following=true;document.body.classList.add('tracking');map.resize();busy=false;display(p);watch=navigator.geolocation.watchPosition(display,e=>say(e.code===1?'Location permission denied. Stop or enable location.':'GPS unavailable · waiting for signal'),{enableHighAccuracy:true,maximumAge:0,timeout:15000})}catch(e){say(e.message)}finally{busy=false;controls()}};
$('reroute').onclick=async()=>{if(busy)return;busy=true;controls();try{const p=await getGps(),from=fix(p).point;if(!inJb(from))throw Error('Current location is outside the JB test area.');busy=false;await requestRoute(from)}catch(e){say(e.message)}finally{busy=false;controls()}};
$('stop').onclick=()=>stop();$('follow').onclick=()=>{following=true;const p=lastFix?.point||origin;if(p)map.easeTo({center:p,zoom:16,duration:500})};window.addEventListener('pagehide',()=>stop(false));document.addEventListener('visibilitychange',()=>{if(document.hidden&&active)say('Test paused in background · waiting for fresh GPS')});setInterval(()=>{if(active&&lastFix&&Date.now()-lastFix.time>10000)say('GPS stale · waiting for a fresh position')},3000);
try{if(!window.maplibregl)throw Error('Map library could not load. Check your connection and reload.');map=new maplibregl.Map({container:'map',center:[103.755,1.49],zoom:12,minZoom:10,maxZoom:19,maxBounds:[[103.40,1.40],[104.1,1.80]],attributionControl:false,style:{version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,maxzoom:19}},layers:[{id:'osm',type:'raster',source:'osm',paint:{'raster-saturation':-.45,'raster-opacity':.9}}]}});map.addControl(new maplibregl.AttributionControl({compact:false,customAttribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}),'top-left');map.on('load',()=>{map.addSource('route',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id:'route-outline',type:'line',source:'route',paint:{'line-color':'#fff','line-width':10}});map.addLayer({id:'route',type:'line',source:'route',paint:{'line-color':'#286bed','line-width':6},layout:{'line-cap':'round','line-join':'round'}});ready=true;say('Map ready. Pick a start and destination in JB.');controls()});map.on('click',e=>{if(!ready||active||busy)return;setPoint([e.lngLat.lng,e.lngLat.lat],select);if(select==='start')select='end';controls()});map.on('dragstart',e=>{if(e.originalEvent)following=false});map.on('error',()=>say('Some map data could not load. Check your connection.'));}catch(e){say(e.message);$('gps').disabled=true}controls();
