// Independent OSM geometry only. Coordinates are [longitude, latitude].
export const inJb = p => Array.isArray(p) && p.length===2 && p.every(Number.isFinite) && p[0]>=103.45 && p[0]<=104.05 && p[1]>=1.43 && p[1]<=1.75;
export function distance(a,b){const r=Math.PI/180,x=(b[1]-a[1])*r,y=(b[0]-a[0])*r,h=Math.sin(x/2)**2+Math.cos(a[1]*r)*Math.cos(b[1]*r)*Math.sin(y/2)**2;return 12742000*Math.asin(Math.min(1,Math.sqrt(h)))}
export function bearing(a,b){const r=Math.PI/180,d=(b[0]-a[0])*r;return (Math.atan2(Math.sin(d)*Math.cos(b[1]*r),Math.cos(a[1]*r)*Math.sin(b[1]*r)-Math.sin(a[1]*r)*Math.cos(b[1]*r)*Math.cos(d))*180/Math.PI+360)%360}
export function cue(m={}){const type=m.type||'',mod=m.modifier||'';if(type==='arrive')return {text:'ARRIVE AT DESTINATION',icon:'◎'};if(type==='depart')return {text:'CONTINUE',icon:'↑'};if(/roundabout|rotary/.test(type))return {text:'ROUNDABOUT'+(m.exit?' · EXIT '+m.exit:''),icon:'⟳'};const action=type==='off ramp'?'TAKE EXIT':type==='fork'?'KEEP':type==='merge'?'MERGE':type==='end of road'?'TURN':type==='turn'?'TURN':'CONTINUE';return {text:(action+' '+mod).trim().toUpperCase(),icon:mod==='uturn'?'↶':mod.includes('left')?'←':mod.includes('right')?'→':'↑'}}
export function adapt(response){if(response.code!=='Ok'||!response.routes?.[0])throw Error('No driving route found. Choose points on accessible JB roads.');const r=response.routes[0],points=[],turns=[];for(const leg of r.legs||[])for(const s of leg.steps||[]){const coords=s.geometry?.coordinates;if(!coords?.length)continue;for(let i=0;i<coords.length;i++){const p=coords[i];if(!inJb(p))throw Error('This route leaves the JB test area. Choose a local JB journey.');if(!points.length||distance(points.at(-1),p)>.01)points.push(p);if(i===0)turns.push({index:points.length-1,name:s.name||s.ref||'Unnamed road',maneuver:s.maneuver,cue:cue(s.maneuver)})}}if(points.length<2)throw Error('Route geometry is unavailable.');const cum=[0];for(let i=1;i<points.length;i++)cum[i]=cum[i-1]+distance(points[i-1],points[i]);return {points,cum,total:cum.at(-1),duration:r.duration,turns:turns.map(t=>({...t,at:cum[t.index]}))}}
export function match(route,p,previous=null,heading=null,speed=0){const mx=111320*Math.cos(p[1]*Math.PI/180),my=110540;let best=null;for(let i=0;i<route.points.length-1;i++){const a=route.points[i],b=route.points[i+1],ax=(a[0]-p[0])*mx,ay=(a[1]-p[1])*my,dx=(b[0]-a[0])*mx,dy=(b[1]-a[1])*my,t=Math.max(0,Math.min(1,-(ax*dx+ay*dy)/(dx*dx+dy*dy||1))),off=Math.hypot(ax+t*dx,ay+t*dy),progress=route.cum[i]+t*(route.cum[i+1]-route.cum[i]);let score=off;if(previous!==null)score+=Math.min(120,Math.abs(progress-previous)*.15);if(Number.isFinite(heading)&&speed>2){const diff=Math.abs(((bearing(a,b)-heading+540)%360)-180);score+=diff*.4}if(!best||score<best.score)best={score,off,progress,index:i,point:[a[0]+t*(b[0]-a[0]),a[1]+t*(b[1]-a[1])]}}return best}
export class Tracker{constructor(route){this.route=route;this.progress=null;this.time=0;this.arrivals=0;this.offFixes=0;this.pending=null;this.confirmations=0;this.confirmedPassed=0}
 update(f,now=Date.now()){if(!f.point?.every(Number.isFinite)||!Number.isFinite(f.accuracy)||f.accuracy>40||!Number.isFinite(f.time)||now-f.time>10000||f.time>now+2000||f.time<=this.time){this.arrivals=0;return {valid:false,status:'Waiting for a fresh, accurate GPS fix'}}const m=match(this.route,f.point,this.progress,f.heading,f.speed);const dt=this.time?(f.time-this.time)/1000:0;this.time=f.time;if(m.off>Math.max(25,f.accuracy)){this.offFixes++;this.arrivals=0;return {valid:false,status:this.offFixes>=3?'Off route · tap Reroute':'Checking road position'}}this.offFixes=0;if(this.progress!==null&&Math.abs(m.progress-this.progress)>Math.max(65,dt*Math.max(15,f.speed||0)*1.8)){this.arrivals=0;return {valid:false,status:'Position uncertain · checking route'}}// Two fixes confirm crossing a maneuver; never consume a turn on one fix.
 const crossed=this.route.turns.filter(t=>t.at<m.progress-8).length;
 if(this.pending===crossed)this.confirmations++;else{this.pending=crossed;this.confirmations=1}
 this.progress=m.progress;if(this.confirmations>=2)this.confirmedPassed=crossed;let next=this.route.turns.slice(this.confirmedPassed).find(t=>t.maneuver?.type!=='depart');
 const remaining=Math.max(0,this.route.total-m.progress);if(remaining<25&&distance(f.point,this.route.points.at(-1))<25&&f.accuracy<=20)this.arrivals++;else this.arrivals=0;return {valid:true,point:m.point,progress:m.progress,remaining,next,turnDistance:next?Math.max(0,next.at-m.progress):remaining,arrived:this.arrivals>=3,status:'GPS active · ±'+Math.round(f.accuracy)+' m'}}}
